name: Tests End-to-end Capyara

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  schedule:
    - cron: '* 8 1 * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
          
      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec cucumber
        

      - name: Get Allure history
        uses: actions/checkout@v2
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: ./logs
          
          allure_report: ./logs
          allure_history: ./logs
          keep_reports: 20

      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
