name: Tests End-to-end Capyara

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
  schedule:
    - cron: '* 8 1 * *'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@477b21f02be01bcb8030d50f37cfec92bfa615b6
        with:
          ruby-version: 2.6
          bundler-cache: true
          
      - name: Install dependencies
        run: bundle install

      - name: Run tests
        run: bundle exec cucumber
        
      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@master
        if: always()
        with:
          allure_results: logs
          allure_history: logs
          keep_reports: 20
          
      - name: Deploy report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v2
        env:
          PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: allure-history
